### ISSUE TITLE
Null value for data envelope references

### ISSUE THREAD

**Issue by SebaDro** [WaCoDiS/core-engine#5]
I noticed that the `WacodisJobFinished` mesage for a land cover classification process contains a `null` value within the `dataEnvelopeReferences` array:
```
{
    "wacodisJobIdentifier": "6185bbc8-5d19-4175-aaa1-aa3b5cb1eb4c",
    "executionFinished": "2020-03-19T00:35:34.220Z",
    "productDescription": {
        "wpsJobIdentifier": "fc2ede9a-2124-438d-9a81-516737efaaf7",
        "outputIdentifiers": [
            "PRODUCT"
        ],
        "productCollection": "land-cover-classification",
        "dataEnvelopeReferences": [
            null,
            "2LOJ7nABttiFjvS8it9a"
        ],
        "processingTool": "de.hsbo.wacodis.land_cover_classification"
    }
}
```
Maybe, this comes from a `StaticSubsetDefinition` that has been defined as one of the inputs for the job which can't be handled properly by the DataAccess API.

**Comment by arnevogt** [comment]
Null references were accidentally added to the list of dataEnvelopeReferences for input resources that have no origin DataEnvelope (e.g. static inputs).

As of commit [ad1b653d220f32bba339c7d0670b4ba628a7ade1](https://github.com/WaCoDiS/core-engine/commit/ad1b653d220f32bba339c7d0670b4ba628a7ade1) null references and empty strings are excluded from the list of dataEnvelopeReferences.
